# Generated by Django 2.2.19 on 2023-04-18 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('-subscribing',)},
        ),
    ]
