# Generated by Django 2.2.19 on 2023-04-24 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20230424_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='recipe',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_shopping_cart', to='recipes.Recipe'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RecipeShoppingCart',
        ),
    ]
