# Generated by Django 2.2.19 on 2023-04-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20230424_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='IngredientShoppingCart',
        ),
    ]
