# Generated by Django 2.2.19 on 2023-04-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20230424_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.CharField(default=1, max_length=1048576),
            preserve_default=False,
        ),
    ]
