# Generated by Django 2.2.19 on 2023-04-24 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
    ]
