# Generated by Django 2.2.19 on 2023-05-10 16:10

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20230510_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True, validators=[recipes.models.validate_color]),
        ),
    ]
